slam_toolbox:
  ros__parameters:

    # =====================
    # Solver / Optimization
    # =====================
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # =====================
    # Frames & Topics
    # =====================
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping
    use_map_saver: true

    # =====================
    # Timing & Publishing
    # =====================
    throttle_scans: 1
    transform_publish_period: 0.05
    map_update_interval: 1.0
    minimum_time_interval: 0.1
    transform_timeout: 0.5
    tf_buffer_duration: 60.0

    # =====================
    # Map Properties
    # =====================
    resolution: 0.05
    max_laser_range: 2.5
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    debug_logging: false

    # =====================
    # Motion Thresholds
    # =====================
    minimum_travel_distance: 0.03
    minimum_travel_heading: 0.05

    # =====================
    # Scan Handling
    # =====================
    use_scan_matching: true
    use_scan_barycenter: true
    scan_queue_size: 20


    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 2.5

    # =====================
    # Loop Closure
    # =====================
    do_loop_closing: false
    loop_search_maximum_distance: 2.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.45
    loop_match_minimum_response_fine: 0.55

    # =====================
    # Correlation Parameters
    # =====================
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05

    # =====================
    # Loop Correlation
    # =====================
    loop_search_space_dimension: 4.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # =====================
    # Scan Matcher Tuning
    # =====================
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
